export const GET_DATA="GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FALURE = "GET_DATA_FALURE";
export const POST_TASKNAME="POST_TASKNAME";
export const REJECT_TASKNAME="REJECT_TASKNAME";
export const DONE_TASKNAME="DONE_TASKNAME";
export const DELELTE_TASKNAME="DELETE_TASKNAME";